### PR TITLE
Attempt to fix compile issue

### PR DESCRIPTION
**Pull request by Littlelies**

### CODE REVIEW

**Comment by khavishbhundoo** [comment]
I was able to compile just fine with latest nginx(1.13.8). Give me more details about the issue you got

**Comment by Littlelies** [comment]
It was with 1.13.7
Got a warning, saying we can't compare an int with a pointer.

**Comment by Littlelies** [comment]
```
/usr/src/upload/nginx-upload-module/ngx_http_upload_module.c: In function 'upload_parse_request_headers':

/usr/src/upload/nginx-upload-module/ngx_http_upload_module.c:3917:109: error: comparison between pointer and integer [-Werror]

  if ((boundary_end_ptr - boundary_start_ptr) >= 2 && boundary_start_ptr[0] == '"' && (boundary_end_ptr - 1) == '"') {

                                                                                                             ^~

cc1: all warnings being treated as errors

make[1]: *** [objs/Makefile:1764: objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1

make: *** [Makefile:8: build] Error 2

make[1]: Leaving directory '/usr/src/nginx-1.13.7'
```

**Comment by khavishbhundoo** [comment]
@Littlelies Check out https://github.com/fdintino/nginx-upload-module .Dintino has been handled the repo.Make all pull request to that repo from now on.

**Pull request closed without merging**
